---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cert-manager
  namespace: app-platform-install
  annotations:
    kapp.k14s.io/change-group: cert-manager
    kapp.k14s.io/change-rule: "delete before deleting serviceaccount"
spec:
  serviceAccountName: app-platform-install-sa
  packageRef:
    refName: cert-manager.community.tanzu.vmware.com
    versionSelection:
      constraints: 1.6.1
      prereleases: {}
